name: officeapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  custom_navigation_bar: ^0.8.2
  device_info_plus: ^9.1.2
  dio: ^5.4.3+1
  dot_navigation_bar: ^1.0.2
  dotted_border: ^2.1.0
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_multiselect: ^1.0.0
  flutter_onboarding_slider: ^1.0.11
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.4
  get: ^4.6.5
  getwidget: ^4.0.0
  hexcolor: ^3.0.1
  http: ^0.13.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  introduction_screen: ^3.1.8

  multi_dropdown: ^2.0.0
  multi_select_flutter: ^4.1.3
  multiselect_dropdown: ^2.0.0+1
  network_info_plus: ^5.0.3
  package_info_plus: ^4.2.0
  shared_preferences: ^2.2.2
  utility: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.jpeg"
  
  assets:
    - assets/images/profile.png
    - assets/images/subordinate.png
    - assets/images/supervisor.png
    - assets/images/task.png
    - assets/images/icon.jpeg



