// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybHvEJYAnHdCjAYHSpc_9fdrF9CvK8z8',
    appId: '1:1085431168877:web:f451e1e167c4b93aa52464',
    messagingSenderId: '1085431168877',
    projectId: 'officeapp-pushnotificati-185e7',
    authDomain: 'officeapp-pushnotificati-185e7.firebaseapp.com',
    storageBucket: 'officeapp-pushnotificati-185e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbaUXaBIB35abaqhiCGB1PpPeER3dnPw',
    appId: '1:1085431168877:android:0036a643f0b6aa37a52464',
    messagingSenderId: '1085431168877',
    projectId: 'officeapp-pushnotificati-185e7',
    storageBucket: 'officeapp-pushnotificati-185e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9SeR_b3IVkCUpH9B74kt2wQFwURFPs40',
    appId: '1:1085431168877:ios:c9b65538b8ccad52a52464',
    messagingSenderId: '1085431168877',
    projectId: 'officeapp-pushnotificati-185e7',
    storageBucket: 'officeapp-pushnotificati-185e7.appspot.com',
    iosBundleId: 'com.example.officeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9SeR_b3IVkCUpH9B74kt2wQFwURFPs40',
    appId: '1:1085431168877:ios:c9b65538b8ccad52a52464',
    messagingSenderId: '1085431168877',
    projectId: 'officeapp-pushnotificati-185e7',
    storageBucket: 'officeapp-pushnotificati-185e7.appspot.com',
    iosBundleId: 'com.example.officeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAybHvEJYAnHdCjAYHSpc_9fdrF9CvK8z8',
    appId: '1:1085431168877:web:d2cfd9b45abd6c93a52464',
    messagingSenderId: '1085431168877',
    projectId: 'officeapp-pushnotificati-185e7',
    authDomain: 'officeapp-pushnotificati-185e7.firebaseapp.com',
    storageBucket: 'officeapp-pushnotificati-185e7.appspot.com',
  );
}
